config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"
  get "about", to: "home#about"
  resources :friends
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :first_name, :last_name, :phone, :user_id ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block", class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block", class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block", class: "form-label" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div>
    <%# form.label :user_id, style: "display: block", class: "form-label" %>
    <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, class: "form-control", type: :hidden %>
  </div>
  <br/>
  <div>
    <%= form.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @friend.first_name %> <%= @friend.last_name%></h5>
    <p class="card-text">Phone: <%= @friend.phone %></p>
    <div class="d-flex gap-2">
      <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-info" %>
      <%= button_to "Delete", @friend, method: :delete, data: {turbo_confirm: "Sure?"}, class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>
<br />
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br/>
<div>
  <%= link_to "Show", @friend, class: "btn btn-info" %>
  <%= link_to "Back to friends", friends_path, class: "btn btn-info" %>
</div>

app/views/friends/index.html.erb
<% content_for :title, "Friends" %>
<br/>
<h1>Friends</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Phone</th>
      <th scope="col">User ID</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <% @friends.each do |friend| %>
    <tbody>
      <tr class="align-middle">
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.user_id %></td>
        <td><%= link_to "Show", friend, class: "btn btn-info" %></td>
        <td><%= link_to "Edit", edit_friend_path(friend), class: "btn btn-info" %></td>
        <td><%= button_to "Delete", friend, method: :delete, data: {turbo_confirm: "Sure?"}, class: "btn btn-info" %></td>
      </tr>
    </tbody>
  <% end %> 
</table>

<%= link_to "Add friend", new_friend_path, class: "btn btn-info" %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>
<br/>
<h1>Add friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-info" %>
</div>

app/views/friends/show.html.erb
<br/>
<%= render @friend %>

<br />
<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-info" %>
</div>

app/views/home/about.html.erb
<h1>The about page</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success mt-3 alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger mt-3 alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary-subtle">
  <div class="container-fluid">
    <%= link_to 'Contacts', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Friends', friends_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex" role="search">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul> 
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Contacts" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% if flash.any? %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>